sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mehmedshehov1998/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mehmedshehov1998/docker-react npm run test
